---
name: build, clang-format, and clang-tidy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        #with:
        #  submodules: "recursive"
      #- name: build xarm
      #  run: make -C libs/xArm-CPLUS-SDK xarm
      #- name: install cmake
      #  run:
      #- name: install grpc and protobuf
      #  run:
      #- name: create a build directory
      #  run: mkdir -p cmake/build
      #- name: generate Makefile
      #  run: cmake -DCMAKE_PREFIX_PATH=~/.local ../..
      #  working-directory: ./cmake/build
      - name: clang-format xarm_daemon.cc
        uses: ./.github/actions/clang-format
        with:
          style: file
          src: "*.cc"
      #- name: clang-tidy
      #  uses: ./.github/actions/clang-tidy
      #  with:
      #    src: "*.cc"
      #    inc: libs
