---
name: run clang-format and clang-tidy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Run clang-format
        uses: ./.github/actions/clang-format
        with:
          style: file
          src: src/xarm-commander.cpp
      - name: Run clang-tidy
        uses: ./.github/actions/clang-tidy
        with:
          src: src/xarm-commander.cpp
          inc: include
