---
name: clang-tidy test

on:
  workflow_dispatch:

jobs:
  run-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: build xarm
        run: make -C libs/xArm-CPLUS-SDK xarm
      - name: clang-tidy
        uses: ./.github/actions/clang-tidy
        with:
          src: src/xarm-commander.cpp
          inc: libs
